name: Lint TS (eslint)

on:
  pull_request:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint TS (eslint)
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./apps/app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        uses: reviewdog/action-eslint@v1
        if: ${{ github.event_name == 'pull_request' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run ESLint
        if: ${{ github.event_name == 'push' }}
        run: npm run lint
