name: Unit Tests (jest)

on:
  pull_request:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Unit Tests (jest)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./apps/app/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run Jest Tests
        run: npm run test
